[phases.setup]
cache = true

[phases.build]
cache = true
command = "npm install --force && npx prisma generate && npm run build"

[phases.start]
command = "npx prisma migrate deploy && npm start"

[build]
cacheDirectories = ["node_modules", "prisma/generated", ".next"]
