[phases.setup]
cache = true

[phases.build]
cache = true
command = "echo 'Starting Build Phase'; npm install --force && npx prisma generate && npm run build"

[phases.start]
command = "echo 'Starting Start Phase'; npx prisma migrate deploy && npm start"

[build]
engine = "nodejs"
