[phases.setup]
cache = true

[phases.build]
cache = false  # Duplicate!
command = "npm install --force && npx prisma generate && npm run build"

[phases.start]
command = "npx prisma migrate deploy && npm start"

[build]
engine = "nodejs"
