services:
  - name: fish-booking-app
    type: web
    env: node
    buildCommand: |
      npm install --force
      npx prisma generate
      npm run build
    startCommand: |
      npx prisma migrate deploy
      npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:nRiylheTCmWRYkpQqkLOPpWsocuSJeUx@${RAILWAY_PRIVATE_DOMAIN}:5432/railway
      - key: NODE_ENV
        value: production
